carproject/carapp/urls.py
from django.urls import path
from . import views
app_name='car'

urlpatterns = [
    path('',views.Home,name='home'),
]

carproject/carproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('carapp.urls')),
    path('auth/',include('userapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

carproject/userapp/urls.py
from django.urls import path
from.import views

app_name='auth'
urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
]

carproject/carapp/models.py
from django.db import models

# Create your models here.

carproject/userapp/models.py
from django.db import models

# Create your models here.

carproject/carapp/views.py
from django.shortcuts import render

# Create your views here.
def Home(req):
    return render(req,'index.html')

carproject/userapp/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib import auth
# Create your views here.
def register(req):
    if req.method=="POST":
        fname=req.POST.get("fname","")
        lname=req.POST.get("lname","")
        email=req.POST.get("email","")
        username=req.POST.get("username","")
        password=req.POST.get("password","")
        cpassword=req.POST.get("cpassword","")
        if password==cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(req,"username already exist")
                return redirect('auth:register')
            elif User.objects.filter(email=email).exists():
                messages.info(req,"email already exist")
                return redirect('auth:register')
            else:
                user=User.objects.create_user(first_name=fname,last_name=lname,email=email,username=username,password=password)
                user.save()
                return redirect('auth:login')
    else:
        messages.info(req,"password not matched")
        return redirect('car:home')
    return render(req,'register.html')
    
    
def login(req):
    if req.method=='POST':
        username=req.POST.get("username","")
        password=req.POST.get("password","")
        user=auth.authenticate(username=username,password=password)
        print(user)
        if user is not None:
            auth.login(req,user)
            print(type(user))
            req.session['user']=str(user)
            return redirect('car:home')
        else:
            messages.info(req,'invalid usernamr or password')
    return render(req,'login.html')


def logout(req):
    auth.logout(req)
    req.session.pop('user',None)
    return redirect('car:home')   

carproject/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>cars</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body>
    {% include "nav.html" %}
    {% block content %}

    {% include "footer.html" %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

carproject/templates/footer.html
{% load static %}
<nav class="navbar bg-dark">
    <div class="container-fluid">
      <span class="navbar-brand mb-0 h1">footer</span>
    </div>
  </nav>
  

carproject/templates/index.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <h1 class="cr">CAR COLLECTIONS</h1>
    <img class="imm" src="../static/images/wallpaperflare.com_wallpaper (1).jpg" alt="">
</body>
</html>
{% endblock %}

carproject/templates/login.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <form class="login mt-5 mb-2" method="post" action="" enctype="multipart/form-data" style="width: 380px;">
        {% csrf_token %}
        <h2 class="lhd">Login</h2>
        <input class="form-control mt-4 mb-3 type="text name="username" placeholder="username">

        <input class="form-control mb-2" type="textr" name="password" placeholder="password">
        <button class="btn btn-success mt-3 mb-2" style="margin-left: 150px;">submit</button>
    </form>
</div>



{% endblock %}

carproject/templates/nav.html
{% load static %}
<nav class="navbar bg-light">
    <div class="container-fluid">
      <a href="{% url 'car:home' %}" class="navbar-brand">Home</a>
      <form class="d-flex" role="search">
        {% if user.is_authenticated %}
        <span class="us me-1">{{user}}</span>
        <a href="{% url 'auth:logout' %}" class="lgot me-2 btn btn-danger">logout</a>
        {% else %}
        <a href="{% url 'auth:register' %}" class="snin me-2 btn btn-dark">sign in</a>
        <a href="{% url 'auth:login' %}" class="lgin btn btn-dark">login</a>
        {% endif %}
      </form>
    </div>
  </nav>

carproject/templates/register.html
{% extends 'base.html' %}
{% block content %}

<form class="frm" action="" method="post" class="bg-light p-3 mt-5 mb-5 rounded sing" style="width: 450px;">
    {% csrf_token %}
    <h2 class="signup text-center">SIGN UP</h2>
    <div class="mb-3">
        <label for="fname" class="form-label">First Name</label>
        <input type="text" class="form-control" id="fname" placeholder="First Name" name="fname">
    </div>
    <div class="mb-3">
        <label for="lname" class="form-label">Last Name</label>
        <input type="text" class="form-control" id="lname" placeholder="Last Name" name="lname">
    </div>
    <div class="mb-3">
        <label for="email" class="form-label">Email</label>
        <input type="email" class="form-control" id="email" placeholder="Email" name="email">
    </div>
    <div class="mb-3">
        <label for="username" class="form-label">Username</label>
        <input type="text" class="form-control" id="username" placeholder="Username" name="username">
    </div>
    <div class="mb-3">
        <label for="password" class="form-label">Password</label>
        <input type="password" class="form-control" id="password" placeholder="Password" name="password">
    </div>
    <div class="mb-3">
        <label for="cpassword" class="form-label">Confirm Password</label>
        <input type="password" class="form-control" id="cpassword" placeholder="Confirm Password" name="cpassword">
    </div>
    <div>
        <button type="submit" class="btn btn-success" style="margin-left: 160px;">Submit</button>
    </div>
</form>

{% endblock %}